In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import tree


In [4]:
df_train = pd.read_csv("datatraining.csv")

In [5]:
df_test = pd.read_csv("datatest2.csv")

In [6]:
print(df_train.shape)
print(df_test.shape)

(8143, 7)
(9752, 7)


In [11]:
X = []
y = []
for row in df_train.iterrows() :
    occupancy = row[1][6] # label (the number visible in the image)
    data = list(row[1][1:6]) # image information as list, without label
    X.append(data)
    y.append(occupancy)

X = np.array(X)
y = np.array(y)
print(len(X))
print(len(y))

8143
8143


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print(len(X_train), len(y_train))
print(X_train[1].shape)

5455 5455
(5,)


In [18]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0] .....
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0] .....
0.9921875


In [19]:
X_new = []
y_new=[]
for row in df_test.iterrows() :
    occupancy=row[1][6]
    data = list(row[1][1:6])
    X_new.append(data)
    y_new.append(occupancy)
X_new = np.array(X_new)
y_new = np.array(y_new)
print(len(X_new))
print(len(df_test))

9752
9752


In [20]:
y_new_pred = clf.predict(X_new)
print(y_new_pred)
print(X_new)

[1 1 1 ... 1 1 1]
[[2.17600000e+01 3.11333333e+01 4.37333333e+02 1.02966667e+03
  5.02101089e-03]
 [2.17900000e+01 3.10000000e+01 4.37333333e+02 1.00000000e+03
  5.00858127e-03]
 [2.17675000e+01 3.11225000e+01 4.34000000e+02 1.00375000e+03
  5.02156913e-03]
 ...
 [2.08900000e+01 2.77450000e+01 4.23500000e+02 1.52150000e+03
  4.23681810e-03]
 [2.08900000e+01 2.80225000e+01 4.18750000e+02 1.63200000e+03
  4.27948547e-03]
 [2.10000000e+01 2.81000000e+01 4.09000000e+02 1.86400000e+03
  4.32073200e-03]]


In [16]:
print(metrics.accuracy_score(y_new, y_new_pred))

0.9458572600492207


In [17]:
y_new_pred = clf.predict(X_new[0:5][:])
print(y_new_pred)

[1 1 1 1 1]


In [27]:
from sklearn.externals import joblib
fn = "occ_det.sav"
joblib.dump(clf, fn)

['occ_det.sav']

In [28]:
model = joblib.load(fn)

In [29]:
model.predict(X_new[0:5][:])

array([1, 1, 1, 1, 1])