In [14]:
import csv

with open('datatest2.txt', 'r') as in_file:
    stripped = (line.strip() for line in in_file)
    lines = (line.split(",") for line in stripped if line)
    with open('datatest2.csv', 'w') as out_file:
        writer = csv.writer(out_file)
        writer.writerow(('title', 'intro'))
        writer.writerows(lines)

In [15]:
import csv

with open('datatest.txt', 'r') as in_file:
    stripped = (line.strip() for line in in_file)
    lines = (line.split(",") for line in stripped if line)
    with open('datatest.csv', 'w') as out_file:
        writer = csv.writer(out_file)
        writer.writerow(('title', 'intro'))
        writer.writerows(lines)

In [50]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import tree


In [51]:
df_train = pd.read_csv("datatraining.csv")

In [52]:
df_test = pd.read_csv("datatest2.csv")

In [53]:
print(df_train.shape)
print(df_test.shape)

(8143, 7)
(9752, 7)


In [54]:
X = []
y = []
for row in df_train.iterrows() :
    occupancy = row[1][6] # label (the number visible in the image)
    data = list(row[1][1:6]) # image information as list, without label
    X.append(data)
    y.append(occupancy)

X = np.array(X)
y = np.array(y)
print(len(X))
print(len(y))

8143
8143


In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print(len(X_train), len(y_train))
print(X_train[1].shape)

5455 5455
(5,)


In [56]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(y_pred[0:20], ".....")
print(y_test[0:20], ".....")
print(metrics.accuracy_score(y_test, y_pred))

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0] .....
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0] .....
0.9925595238095238


In [57]:
X_new = []
y_new=[]
for row in df_test.iterrows() :
    occupancy=row[1][6]
    data = list(row[1][1:6])
    X_new.append(data)
    y_new.append(occupancy)
X_new = np.array(X_new)
y_new = np.array(y_new)
print(len(X_new))
print(len(df_test))

9752
9752


In [58]:
y_new_pred = clf.predict(X_new)
print(y_new_pred)

[1 1 1 ... 1 1 1]


In [59]:
print(metrics.accuracy_score(y_new, y_new_pred))

0.9460623461853979
